import type { AutocompleteOption } from '@/components/common/Autocomplete';

// Comprehensive list of common occupations in Sweden
export const COMMON_OCCUPATIONS: AutocompleteOption[] = [
  // Administration & Kontor
  { id: '1', label: 'Administratör' },
  { id: '2', label: 'Administrativ chef' },
  { id: '3', label: 'Assistent' },
  { id: '4', label: 'Chefsekretetare' },
  { id: '5', label: 'Controller' },
  { id: '6', label: 'Dokumentcontroller' },
  { id: '7', label: 'Ekonomiassistent' },
  { id: '8', label: 'Ekonom' },
  { id: '9', label: 'Ekonomichef' },
  { id: '10', label: 'HR-administratör' },
  { id: '11', label: 'HR-assistent' },
  { id: '12', label: 'HR-specialist' },
  { id: '13', label: 'HR-chef' },
  { id: '14', label: 'Inköpare' },
  { id: '15', label: 'Inköpschef' },
  { id: '16', label: 'Kanslichef' },
  { id: '17', label: 'Kassör' },
  { id: '18', label: 'Kontorschef' },
  { id: '19', label: 'Löneadministratör' },
  { id: '20', label: 'Lönekonsult' },
  { id: '21', label: 'Office manager' },
  { id: '22', label: 'Projektadministratör' },
  { id: '23', label: 'Projektkoordinator' },
  { id: '24', label: 'Receptionist' },
  { id: '25', label: 'Redovisningsassistent' },
  { id: '26', label: 'Redovisningskonsult' },
  { id: '27', label: 'Redovisningsekonom' },
  { id: '28', label: 'Sekreterare' },
  { id: '29', label: 'Verksamhetscontroller' },
  { id: '30', label: 'Verksamhetsutvecklare' },

  // Försäljning & Marknad
  { id: '31', label: 'Account manager' },
  { id: '32', label: 'Affärsutvecklare' },
  { id: '33', label: 'Butikschef' },
  { id: '34', label: 'Butikssäljare' },
  { id: '35', label: 'Category manager' },
  { id: '36', label: 'Channel manager' },
  { id: '37', label: 'Customer success manager' },
  { id: '38', label: 'Försäljningschef' },
  { id: '39', label: 'Försäljningsdirektör' },
  { id: '40', label: 'Försäljningsingenjör' },
  { id: '41', label: 'Försäljningskonsult' },
  { id: '42', label: 'Försäljningskoordinator' },
  { id: '43', label: 'Key account manager' },
  { id: '44', label: 'Kundansvarig' },
  { id: '45', label: 'Kundbefattningshavare' },
  { id: '46', label: 'Kundtjänstchef' },
  { id: '47', label: 'Kundtjänstmedarbetare' },
  { id: '48', label: 'Marknadsanalytiker' },
  { id: '49', label: 'Marknadsassistent' },
  { id: '50', label: 'Marknadschef' },
  { id: '51', label: 'Marknadskoordinator' },
  { id: '52', label: 'Marknadskommunikatör' },
  { id: '53', label: 'Mediasäljare' },
  { id: '54', label: 'Produktspecialist' },
  { id: '55', label: 'Regionchef' },
  { id: '56', label: 'Relationsansvarig' },
  { id: '57', label: 'Säljare' },
  { id: '58', label: 'Säljassistent' },
  { id: '59', label: 'Säljchef' },
  { id: '60', label: 'Säljkoordinator' },
  { id: '61', label: 'Säljledare' },
  { id: '62', label: 'Säljprojektledare' },
  { id: '63', label: 'Säljregionschef' },
  { id: '64', label: 'Säljrepresentant' },
  { id: '65', label: 'Telefonförsäljare' },
  { id: '66', label: 'Visuell merchandiser' },

  // IT & Teknik
  { id: '67', label: 'Apputvecklare' },
  { id: '68', label: 'Backendutvecklare' },
  { id: '69', label: 'BI-utvecklare' },
  { id: '70', label: 'Business analyst' },
  { id: '71', label: 'Chief technology officer' },
  { id: '72', label: 'Cloud engineer' },
  { id: '73', label: 'Data engineer' },
  { id: '74', label: 'Dataanalytiker' },
  { id: '75', label: 'Datascientist' },
  { id: '76', label: 'DevOps engineer' },
  { id: '77', label: 'Frontendutvecklare' },
  { id: '78', label: 'Fullstackutvecklare' },
  { id: '79', label: 'GIS-utvecklare' },
  { id: '80', label: 'Helpdesktekniker' },
  { id: '81', label: 'IT-arkitekt' },
  { id: '82', label: 'IT-chef' },
  { id: '83', label: 'IT-drifttekniker' },
  { id: '84', label: 'IT-koordinator' },
  { id: '85', label: 'IT-projektledare' },
  { id: '86', label: 'IT-säkerhetsansvarig' },
  { id: '87', label: 'IT-tekniker' },
  { id: '88', label: 'Javautvecklare' },
  { id: '89', label: 'Mjukvaruarkitekt' },
  { id: '90', label: 'Mjukvaruutvecklare' },
  { id: '91', label: 'Nätverksadministratör' },
  { id: '92', label: 'Nätverkstekniker' },
  { id: '93', label: 'PHP-utvecklare' },
  { id: '94', label: 'Produktägare' },
  { id: '95', label: 'Pythonutvecklare' },
  { id: '96', label: 'QA-engineer' },
  { id: '97', label: 'Reactutvecklare' },
  { id: '98', label: 'Release manager' },
  { id: '99', label: 'Scrum master' },
  { id: '100', label: 'Servicedeskmedarbetare' },
  { id: '101', label: 'Site reliability engineer' },
  { id: '102', label: 'Supporttekniker' },
  { id: '103', label: 'Systemadministratör' },
  { id: '104', label: 'Systemanalytiker' },
  { id: '105', label: 'Systemarkitekt' },
  { id: '106', label: 'Systemutvecklare' },
  { id: '107', label: 'Systemförvaltare' },
  { id: '108', label: 'Systemtestare' },
  { id: '109', label: 'Tech lead' },
  { id: '110', label: 'Testautomatiserare' },
  { id: '111', label: 'Testare' },
  { id: '112', label: 'Testledare' },
  { id: '113', label: 'UI-designer' },
  { id: '114', label: 'UX-designer' },
  { id: '115', label: 'UX-researcher' },
  { id: '116', label: 'Webbdesigner' },
  { id: '117', label: 'Webbutvecklare' },

  // Vård & Hälsa
  { id: '118', label: 'Ambulanssjukvårdare' },
  { id: '119', label: 'Anestesisjuksköterska' },
  { id: '120', label: 'Arbetsterapeut' },
  { id: '121', label: 'Audionom' },
  { id: '122', label: 'Barnmorska' },
  { id: '123', label: 'Barnsjuksköterska' },
  { id: '124', label: 'Behandlingsassistent' },
  { id: '125', label: 'Beteendevetare' },
  { id: '126', label: 'Biomedicinsk analytiker' },
  { id: '127', label: 'Dietist' },
  { id: '128', label: 'Distriktssköterska' },
  { id: '129', label: 'Fysioterapeut' },
  { id: '130', label: 'Habiliteringsassistent' },
  { id: '131', label: 'Hemtjänstassistent' },
  { id: '132', label: 'Hjälpmedelstekniker' },
  { id: '133', label: 'Intensivvårdssjuksköterska' },
  { id: '134', label: 'Kurator' },
  { id: '135', label: 'Läkare' },
  { id: '136', label: 'Läkarsekreterare' },
  { id: '137', label: 'Medicinsk sekreterare' },
  { id: '138', label: 'Mentalvårdare' },
  { id: '139', label: 'Operationssjuksköterska' },
  { id: '140', label: 'Optiker' },
  { id: '141', label: 'Personlig assistent' },
  { id: '142', label: 'Psykolog' },
  { id: '143', label: 'Psykoterapeut' },
  { id: '144', label: 'Receptionist vårdcentral' },
  { id: '145', label: 'Röntgensjuksköterska' },
  { id: '146', label: 'Sjukgymnast' },
  { id: '147', label: 'Sjuksköterska' },
  { id: '148', label: 'Skolsköterska' },
  { id: '149', label: 'Socionom' },
  { id: '150', label: ' specialistsjuksköterska' },
  { id: '151', label: 'Tandhygienist' },
  { id: '152', label: 'Tandsköterska' },
  { id: '153', label: 'Tandtekniker' },
  { id: '154', label: 'Undersköterska' },
  { id: '155', label: 'Vårdadministratör' },
  { id: '156', label: 'Vårdbiträde' },
  { id: '157', label: 'Vårdenhetschef' },
  { id: '158', label: 'Vårdledare' },
  { id: '159', label: 'Vårdpedagog' },

  // Utbildning
  { id: '160', label: 'Biträdande rektor' },
  { id: '161', label: 'Barnskötare' },
  { id: '162', label: 'Elevassistent' },
  { id: '163', label: 'Förskolechef' },
  { id: '164', label: 'Förskollärare' },
  { id: '165', label: 'Fritidspedagog' },
  { id: '166', label: 'Grundskollärare' },
  { id: '167', label: 'Gymnasielärare' },
  { id: '168', label: 'Kursadministratör' },
  { id: '169', label: 'Lärare' },
  { id: '170', label: 'Lärarvikarie' },
  { id: '171', label: 'Modersmålslärare' },
  { id: '172', label: 'Rektor' },
  { id: '173', label: 'Skoladministratör' },
  { id: '174', label: 'Skolbibliotekarie' },
  { id: '175', label: 'Skolsköterska' },
  { id: '176', label: 'Skolskötare' },
  { id: '177', label: 'Specialpedagog' },
  { id: '178', label: 'Speciallärare' },
  { id: '179', label: 'Studie- och yrkesvägledare' },
  { id: '180', label: 'Studievägledare' },
  { id: '181', label: 'Utbildare' },
  { id: '182', label: 'Utbildningsadministratör' },
  { id: '183', label: 'Utbildningsansvarig' },
  { id: '184', label: 'Utbildningschef' },
  { id: '185', label: 'Utbildningskoordinator' },
  { id: '186', label: 'Utbildningsledare' },
  { id: '187', label: 'Vikarierande lärare' },

  // Bygg & Anläggning
  { id: '188', label: 'Anläggningsarbetare' },
  { id: '189', label: 'Anläggningsingenjör' },
  { id: '190', label: 'Arbetsledare bygg' },
  { id: '191', label: 'Betongarbetare' },
  { id: '192', label: 'Betongare' },
  { id: '193', label: 'Bilmekaniker' },
  { id: '194', label: 'Byggarbetare' },
  { id: '195', label: 'Byggchefsingenjör' },
  { id: '196', label: 'Byggnadsmålare' },
  { id: '197', label: 'Byggnadsarbetare' },
  { id: '198', label: 'Byggnadsingenjör' },
  { id: '199', label: 'Byggnadsplåtslagare' },
  { id: '200', label: 'Byggnadsritare' },
  { id: '201', label: 'Byggnadssnickare' },
  { id: '202', label: 'Byggnadstekniker' },
  { id: '203', label: 'Driftchef fastighet' },
  { id: '204', label: 'Elektriker' },
  { id: '205', label: 'Fastighetsingenjör' },
  { id: '206', label: 'Fastighetsmäklare' },
  { id: '207', label: 'Fastighetsskötare' },
  { id: '208', label: 'Fastighetstekniker' },
  { id: '209', label: 'Fastighetsvärderare' },
  { id: '210', label: 'Fordonsmekaniker' },
  { id: '211', label: 'Golvläggare' },
  { id: '212', label: 'Hantverkare' },
  { id: '213', label: 'Industrisnickare' },
  { id: '214', label: 'Isoleringsmontör' },
  { id: '215', label: 'Kranförare' },
  { id: '216', label: 'Kylmontör' },
  { id: '217', label: 'Källarmästare' },
  { id: '218', label: 'Mekaniker' },
  { id: '219', label: 'Montör' },
  { id: '220', label: 'Målare' },
  { id: '221', label: 'Plåtslagare' },
  { id: '222', label: 'Projekteringsledare' },
  { id: '223', label: 'Projektledare bygg' },
  { id: '224', label: 'Platschef' },
  { id: '225', label: 'Rivningsarbetare' },
  { id: '226', label: 'Rörmokare' },
  { id: '227', label: 'Servicetekniker' },
  { id: '228', label: 'Skadesanerare' },
  { id: '229', label: 'Snickare' },
  { id: '230', label: 'Ställningsbyggare' },
  { id: '231', label: 'Svetsare' },
  { id: '232', label: 'Takmontör' },
  { id: '233', label: 'Truckförare' },
  { id: '234', label: 'Ventilationsmontör' },
  { id: '235', label: 'Ventilationstekniker' },
  { id: '236', label: 'Vvs-montör' },
  { id: '237', label: 'Vvs-tekniker' },

  // Industri & Produktion
  { id: '238', label: 'Arbetsledare industri' },
  { id: '239', label: 'Arbetare' },
  { id: '240', label: 'Bandsågare' },
  { id: '241', label: 'CNC-operatör' },
  { id: '242', label: 'Driftchef' },
  { id: '243', label: 'Driftledare' },
  { id: '244', label: 'Drifttekniker' },
  { id: '245', label: 'Fabriksarbetare' },
  { id: '246', label: 'Förbandsarbetare' },
  { id: '247', label: 'Industriarbetare' },
  { id: '248', label: 'Industrielektriker' },
  { id: '249', label: 'Industrirengöring' },
  { id: '250', label: 'Kemist' },
  { id: '251', label: 'Kvalitetsansvarig' },
  { id: '252', label: 'Kvalitetschef' },
  { id: '253', label: 'Kvalitetsingenjör' },
  { id: '254', label: 'Kvalitetstekniker' },
  { id: '255', label: 'Laborant' },
  { id: '256', label: 'Lackerare' },
  { id: '257', label: 'Lagerarbetare' },
  { id: '258', label: 'Lagerchef' },
  { id: '259', label: 'Logistikansvarig' },
  { id: '260', label: 'Logistikchef' },
  { id: '261', label: 'Logistiker' },
  { id: '262', label: 'Logistikkoordinator' },
  { id: '263', label: 'Maskinbefäl' },
  { id: '264', label: 'Maskinförare' },
  { id: '265', label: 'Maskinoperatör' },
  { id: '266', label: 'Maskinreparatör' },
  { id: '267', label: 'Maskinsetter' },
  { id: '268', label: 'Materialplanerare' },
  { id: '269', label: 'Mekaniker' },
  { id: '270', label: 'Packare' },
  { id: '271', label: 'Processoperatör' },
  { id: '272', label: 'Produktionsarbetare' },
  { id: '273', label: 'Produktionschef' },
  { id: '274', label: 'Produktionsingenjör' },
  { id: '275', label: 'Produktionsledare' },
  { id: '276', label: 'Produktionsplanerare' },
  { id: '277', label: 'Produktionstekniker' },
  { id: '278', label: 'Skiftledare' },
  { id: '279', label: 'Supply chain manager' },
  { id: '280', label: 'Transportledare' },
  { id: '281', label: 'Transportplanerare' },
  { id: '282', label: 'Tulldeklarant' },
  { id: '283', label: 'Underhållsansvarig' },
  { id: '284', label: 'Underhållschef' },
  { id: '285', label: 'Underhållsledare' },
  { id: '286', label: 'Underhållstekniker' },
  { id: '287', label: 'Verkstadsarbetare' },
  { id: '288', label: 'Verkstadsingenjör' },
  { id: '289', label: 'Verkmästare' },

  // Transport & Logistik
  { id: '290', label: 'Bilförare' },
  { id: '291', label: 'Budbilsförare' },
  { id: '292', label: 'Buschaufför' },
  { id: '293', label: 'Chaufför' },
  { id: '294', label: 'Distributionselektriker' },
  { id: '295', label: 'Distributionsförare' },
  { id: '296', label: 'Fjärrförare' },
  { id: '297', label: 'Färjelots' },
  { id: '298', label: 'Godshanterare' },
  { id: '299', label: 'Kranförare' },
  { id: '300', label: 'Lastbilschaufför' },
  { id: '301', label: 'Lastbilsförare' },
  { id: '302', label: 'Linjechaufför' },
  { id: '303', label: 'Lokalvårdare' },
  { id: '304', label: 'Pilot' },
  { id: '305', label: 'Speditör' },
  { id: '306', label: 'Stuveriarbetare' },
  { id: '307', label: 'Taxiförare' },
  { id: '308', label: 'Trafikledare' },
  { id: '309', label: 'Truckförare' },
  { id: '310', label: 'Åkerichef' },

  // Hotell & Restaurang
  { id: '311', label: 'Bagare' },
  { id: '312', label: 'Barista' },
  { id: '313', label: 'Bartender' },
  { id: '314', label: 'Buffévärdinna' },
  { id: '315', label: 'Cafébiträde' },
  { id: '316', label: 'Cateringansvarig' },
  { id: '317', label: 'Conferencier' },
  { id: '318', label: 'Diskare' },
  { id: '319', label: 'Egenföretagare restaurang' },
  { id: '320', label: 'Eldare' },
  { id: '321', label: 'Fastighetsskötare' },
  { id: '322', label: 'Florist' },
  { id: '323', label: 'Frukostvärdinna' },
  { id: '324', label: 'Grillkock' },
  { id: '325', label: 'Hotellchef' },
  { id: '326', label: 'Hotellreceptionist' },
  { id: '327', label: 'Hotellstädare' },
  { id: '328', label: 'Hovmästare' },
  { id: '329', label: 'Kallskänka' },
  { id: '330', label: 'Kock' },
  { id: '331', label: 'Köksansvarig' },
  { id: '332', label: 'Köksbiträde' },
  { id: '333', label: 'Köksmästare' },
  { id: '334', label: 'Mattläggare' },
  { id: '335', label: 'Nattportier' },
  { id: '336', label: 'Pizzabagare' },
  { id: '337', label: 'Restaurangbiträde' },
  { id: '338', label: 'Restaurangchef' },
  { id: '339', label: 'Restaurangföreståndare' },
  { id: '340', label: 'Room service' },
  { id: '341', label: 'Servitör' },
  { id: '342', label: 'Servitris' },
  { id: '343', label: 'Sommelier' },
  { id: '344', label: 'Souschef' },
  { id: '345', label: 'Städare' },
  { id: '346', label: 'Städledare' },
  { id: '347', label: 'Sushi-kock' },
  { id: '348', label: 'Trädgårdsanläggare' },
  { id: '349', label: 'Trädgårdsarbetare' },
  { id: '350', label: 'Trädgårdsmästare' },
  { id: '351', label: 'Vaktmästare' },
  { id: '352', label: 'Varuhusstädare' },

  // Städ & Service
  { id: '353', label: 'Flyttstädare' },
  { id: '354', label: 'Fönsterputsare' },
  { id: '355', label: 'Hemstädare' },
  { id: '356', label: 'Industristädare' },
  { id: '357', label: 'Kontorsstädare' },
  { id: '358', label: 'Lokalvårdare' },
  { id: '359', label: 'Skolstädare' },
  { id: '360', label: 'Städare' },
  { id: '361', label: 'Städledare' },
  { id: '362', label: 'Trappstädare' },
  { id: '363', label: 'Tvätteriarbetare' },

  // Media & Kommunikation
  { id: '364', label: 'Art director' },
  { id: '365', label: 'Content manager' },
  { id: '366', label: 'Content producer' },
  { id: '367', label: 'Copywriter' },
  { id: '368', label: 'Digital marketing specialist' },
  { id: '369', label: 'Fotograf' },
  { id: '370', label: 'Grafisk designer' },
  { id: '371', label: 'Illustratör' },
  { id: '372', label: 'Journalist' },
  { id: '373', label: 'Kommunikatör' },
  { id: '374', label: 'Kreativ chef' },
  { id: '375', label: 'Ljudtekniker' },
  { id: '376', label: 'Ljussättare' },
  { id: '377', label: 'Marknadsförare' },
  { id: '378', label: 'Media planner' },
  { id: '379', label: 'Medieproducent' },
  { id: '380', label: 'Medietekniker' },
  { id: '381', label: 'PR-assistent' },
  { id: '382', label: 'PR-chef' },
  { id: '383', label: 'PR-konsult' },
  { id: '384', label: 'Pressansvarig' },
  { id: '385', label: 'Pressfotograf' },
  { id: '386', label: 'Radiojournalist' },
  { id: '387', label: 'Radioproducent' },
  { id: '388', label: 'Redaktionschef' },
  { id: '389', label: 'Redaktionssekreterare' },
  { id: '390', label: 'Redaktör' },
  { id: '391', label: 'Reporter' },
  { id: '392', label: 'SEO-specialist' },
  { id: '393', label: 'Social media manager' },
  { id: '394', label: 'Streamingtekniker' },
  { id: '395', label: 'Technical writer' },
  { id: '396', label: 'Tekniker' },
  { id: '397', label: 'Textilarbetare' },
  { id: '398', label: 'TV-journalist' },
  { id: '399', label: 'TV-producent' },
  { id: '400', label: 'Videograf' },
  { id: '401', label: 'Videoredigerare' },
  { id: '402', label: 'Webbeditor' },
  { id: '403', label: 'Webbredaktör' },
  { id: '404', label: 'Översättare' },

  // Juridik & Säkerhet
  { id: '405', label: 'Advokat' },
  { id: '406', label: 'Advokatsekreterare' },
  { id: '407', label: 'Bevakningschef' },
  { id: '408', label: 'Bevakningspersonal' },
  { id: '409', label: 'Brandman' },
  { id: '410', label: 'Brandinspektör' },
  { id: '411', label: 'Brandingenjör' },
  { id: '412', label: 'Compliance officer' },
  { id: '413', label: 'Fältassistent' },
  { id: '414', label: 'Försäkringshandläggare' },
  { id: '415', label: 'Försäkringskonsulent' },
  { id: '416', label: 'Försäkringsrådgivare' },
  { id: '417', label: 'Handläggare' },
  { id: '418', label: 'Jurist' },
  { id: '419', label: 'Juristassistent' },
  { id: '420', label: 'Kriminalvårdare' },
  { id: '421', label: 'Myndighetsutövare' },
  { id: '422', label: 'Notarie' },
  { id: '423', label: 'Ordningsvakt' },
  { id: '424', label: 'Polis' },
  { id: '425', label: 'Rättssakkunnig' },
  { id: '426', label: 'Rättsläkare' },
  { id: '427', label: 'Säkerhetsansvarig' },
  { id: '428', label: 'Säkerhetschef' },
  { id: '429', label: 'Säkerhetskonsult' },
  { id: '430', label: 'Säkerhetskoordinator' },
  { id: '431', label: 'Väktare' },

  // Teknik & Ingenjör
  { id: '432', label: 'Applikationsingenjör' },
  { id: '433', label: 'Arkitekt' },
  { id: '434', label: 'Automationstekniker' },
  { id: '435', label: 'Beräkningsingenjör' },
  { id: '436', label: 'Civilingenjör' },
  { id: '437', label: 'Driftchef' },
  { id: '438', label: 'Driftsingenjör' },
  { id: '439', label: 'Elarbetare' },
  { id: '440', label: 'Elektroingenjör' },
  { id: '441', label: 'Elingenjör' },
  { id: '442', label: 'Fältsäljare' },
  { id: '443', label: 'Fälttekniker' },
  { id: '444', label: 'Högskoleingenjör' },
  { id: '445', label: 'Ingenjör' },
  { id: '446', label: 'Konstruktionsingenjör' },
  { id: '447', label: 'Konstruktör' },
  { id: '448', label: 'Kvalitetsingenjör' },
  { id: '449', label: 'Landskapsarkitekt' },
  { id: '450', label: 'Maskiningenjör' },
  { id: '451', label: 'Miljöingenjör' },
  { id: '452', label: 'Projekteringsingenjör' },
  { id: '453', label: 'Projektingenjör' },
  { id: '454', label: 'Projektör' },
  { id: '455', label: 'Provningsingenjör' },
  { id: '456', label: 'Rymdingenjör' },
  { id: '457', label: 'Serviceingenjör' },
  { id: '458', label: 'Sjöingenjör' },
  { id: '459', label: 'Systemingenjör' },
  { id: '460', label: 'Tekniker' },
  { id: '461', label: 'Teknisk chef' },
  { id: '462', label: 'Teknisk konsult' },
  { id: '463', label: 'Teknisk säljare' },
  { id: '464', label: 'Tekniskt ansvarig' },
  { id: '465', label: 'Tillverkningsingenjör' },

  // Ledning & Chefer
  { id: '466', label: 'Affärsområdeschef' },
  { id: '467', label: 'Avdelningschef' },
  { id: '468', label: 'Biträdande chef' },
  { id: '469', label: 'Bolagschef' },
  { id: '470', label: 'Business controller' },
  { id: '471', label: 'Business development manager' },
  { id: '472', label: 'Business manager' },
  { id: '473', label: 'Chef' },
  { id: '474', label: 'Chefsassistent' },
  { id: '475', label: 'Driftchef' },
  { id: '476', label: 'Enhetschef' },
  { id: '477', label: 'Finanschef' },
  { id: '478', label: 'Företagsledare' },
  { id: '479', label: 'Försäljningsdirektör' },
  { id: '480', label: 'General manager' },
  { id: '481', label: 'Gruppchef' },
  { id: '482', label: 'Koncernchef' },
  { id: '483', label: 'Kontorschef' },
  { id: '484', label: 'Ledningsassistent' },
  { id: '485', label: 'Managementkonsult' },
  { id: '486', label: 'Mellanchef' },
  { id: '487', label: 'Operativ chef' },
  { id: '488', label: 'Personalchef' },
  { id: '489', label: 'Produktionschef' },
  { id: '490', label: 'Projektchef' },
  { id: '491', label: 'Regionchef' },
  { id: '492', label: 'Servicechef' },
  { id: '493', label: 'Säljdirektör' },
  { id: '494', label: 'Team leader' },
  { id: '495', label: 'Teamledare' },
  { id: '496', label: 'Teknisk chef' },
  { id: '497', label: 'Verkställande direktör' },
  { id: '498', label: 'Vice VD' },
  { id: '499', label: 'VD' },
  { id: '500', label: 'VD-assistent' },

  // Kultur & Konst
  { id: '501', label: 'Antikvarie' },
  { id: '502', label: 'Arkivassistent' },
  { id: '503', label: 'Arkivarie' },
  { id: '504', label: 'Arrangör' },
  { id: '505', label: 'Balettdansör' },
  { id: '506', label: 'Bibliotekarie' },
  { id: '507', label: 'Bildkonstnär' },
  { id: '508', label: 'Bildlärare' },
  { id: '509', label: 'Bokbindare' },
  { id: '510', label: 'Bokhandlare' },
  { id: '511', label: 'Bokrevisor' },
  { id: '512', label: 'Casinovärd' },
  { id: '513', label: 'Chaufför' },
  { id: '514', label: 'Ciceron' },
  { id: '515', label: 'Clown' },
  { id: '516', label: 'Comedian' },
  { id: '517', label: 'Conservator' },
  { id: '518', label: 'Croupier' },
  { id: '519', label: 'Curator' },
  { id: '520', label: 'Dansare' },
  { id: '521', label: 'Danslärare' },
  { id: '522', label: 'Designer' },
  { id: '523', label: 'Dirigent' },
  { id: '524', label: 'DJ' },
  { id: '525', label: 'Dokumentärfilmare' },
  { id: '526', label: 'Dragspelare' },
  { id: '527', label: 'Eventkoordinator' },
  { id: '528', label: 'Eventpersonal' },
  { id: '529', label: 'Fäktare' },
  { id: '530', label: 'Författare' },
  { id: '531', label: 'Gallerist' },
  { id: '532', label: 'Gitarrlärare' },
  { id: '533', label: 'Gitarrrist' },
  { id: '534', label: 'Glasmästare' },
  { id: '535', label: 'Grafiker' },
  { id: '536', label: 'Guldsmed' },
  { id: '537', label: 'Historiker' },
  { id: '538', label: 'Hovtornist' },
  { id: '539', label: 'Illustratör' },
  { id: '540', label: 'Instrumentmakare' },
  { id: '541', label: 'Kalligraf' },
  { id: '542', label: 'Keramiker' },
  { id: '543', label: 'Keyboardist' },
  { id: '544', label: 'Kläddesigner' },
  { id: '545', label: 'Klätterinstruktör' },
  { id: '546', label: 'Kompositör' },
  { id: '547', label: 'Konstnär' },
  { id: '548', label: 'Koreograf' },
  { id: '549', label: 'Kulturkonsulent' },
  { id: '550', label: 'Kulturpedagog' },
  { id: '551', label: 'Ljuddesigner' },
  { id: '552', label: 'Ljudtekniker' },
  { id: '553', label: 'Ljustekniker' },
  { id: '554', label: 'Ljussättare' },
  { id: '555', label: 'Lokalvårdare museum' },
  { id: '556', label: 'Magiker' },
  { id: '557', label: 'Målare konstnär' },
  { id: '558', label: 'Modedesigner' },
  { id: '559', label: 'Museiassistent' },
  { id: '560', label: 'Museiguide' },
  { id: '561', label: 'Museitekniker' },
  { id: '562', label: 'Musiker' },
  { id: '563', label: 'Musikjournalist' },
  { id: '564', label: 'Musiklärare' },
  { id: '565', label: 'Musikpedagog' },
  { id: '566', label: 'Musikproducent' },
  { id: '567', label: 'Musikterapeut' },
  { id: '568', label: 'Orkesterledare' },
  { id: '569', label: 'Orkestermusiker' },
  { id: '570', label: 'Penninglotteriförsäljare' },
  { id: '571', label: 'Pianist' },
  { id: '572', label: 'Pianostämmare' },
  { id: '573', label: 'Pianolärare' },
  { id: '574', label: 'Plåtslagare konst' },
  { id: '575', label: 'Poet' },
  { id: '576', label: 'Popartist' },
  { id: '577', label: 'Producent' },
  { id: '578', label: 'Regissör' },
  { id: '579', label: 'Rekvisitör' },
  { id: '580', label: 'Ridlärare' },
  { id: '581', label: 'Riksdagsledamot' },
  { id: '582', label: 'Rockmusiker' },
  { id: '583', label: 'Scenarbetare' },
  { id: '584', label: 'Scenograf' },
  { id: '585', label: 'Scentekniker' },
  { id: '586', label: 'Sculptör' },
  { id: '587', label: 'Simsällskapsinstruktör' },
  { id: '588', label: 'Simsällskapstränare' },
  { id: '589', label: 'Sångare' },
  { id: '590', label: 'Sånglärare' },
  { id: '591', label: 'Sångtextförfattare' },
  { id: '592', label: 'Textilkonstnär' },
  { id: '593', label: 'Trädgårdsarkitekt' },
  { id: '594', label: 'Trädgårdsdesigner' },
  { id: '595', label: 'Träskulptör' },
  { id: '596', label: 'Trubadur' },
  { id: '597', label: 'Tungmetallmusiker' },
  { id: '598', label: 'Turnéledare' },
  { id: '599', label: 'Tv-producent' },
  { id: '600', label: 'Urmakare' },

  // Vetenskap & Forskning
  { id: '601', label: 'Anatom' },
  { id: '602', label: 'Antropolog' },
  { id: '603', label: 'Archeolog' },
  { id: '604', label: 'Astronom' },
  { id: '605', label: 'Biokemist' },
  { id: '606', label: 'Biolog' },
  { id: '607', label: 'Botaniker' },
  { id: '608', label: 'Ekolog' },
  { id: '609', label: 'Fysiker' },
  { id: '610', label: 'Forskare' },
  { id: '611', label: 'Forskningsassistent' },
  { id: '612', label: 'Forskningschef' },
  { id: '613', label: 'Forskningsingenjör' },
  { id: '614', label: 'Forskningskoordinator' },
  { id: '615', label: 'Geolog' },
  { id: '616', label: 'Kemist' },
  { id: '617', label: 'Klimatforskare' },
  { id: '618', label: 'Läkemedelskemist' },
  { id: '619', label: 'Marinbiolog' },
  { id: '620', label: 'Matematiker' },
  { id: '621', label: 'Meteorolog' },
  { id: '622', label: 'Mikrobiolog' },
  { id: '623', label: 'Naturvårdsbiolog' },
  { id: '624', label: 'Neurolog' },
  { id: '625', label: 'Neurovetare' },
  { id: '626', label: 'Odlare' },
  { id: '627', label: 'Paleontolog' },
  { id: '628', label: 'Patolog' },
  { id: '629', label: 'Farmakolog' },
  { id: '630', label: 'Psykiater' },
  { id: '631', label: 'Radiolog' },
  { id: '632', label: 'Sjukdomsforskare' },
  { id: '633', label: 'Statistiker' },
  { id: '634', label: 'Toxikolog' },
  { id: '635', label: 'Zoolog' },

  // Miljö & Naturvård
  { id: '636', label: 'Arborist' },
  { id: '637', label: 'Avfallshanterare' },
  { id: '638', label: 'Biolog' },
  { id: '639', label: 'Djurparksveterinär' },
  { id: '640', label: 'Djurvårdare' },
  { id: '641', label: 'Energiingenjör' },
  { id: '642', label: 'Energikonsult' },
  { id: '643', label: 'Entreprenör skogsbruk' },
  { id: '644', label: 'Fiskearbetare' },
  { id: '645', label: 'Fiskeodlare' },
  { id: '646', label: 'Förvaltare naturreservat' },
  { id: '647', label: 'Hunddagisägare' },
  { id: '648', label: 'Hundfrisör' },
  { id: '649', label: 'Hundtränare' },
  { id: '650', label: 'Hästskötare' },
  { id: '651', label: 'Hästtränare' },
  { id: '652', label: 'Jägmästare' },
  { id: '653', label: 'Kennelägare' },
  { id: '654', label: 'Klimatanalytiker' },
  { id: '655', label: 'Klimatstrateg' },
  { id: '656', label: 'Lantbrukare' },
  { id: '657', label: 'Lantmätare' },
  { id: '658', label: 'Miljöarbetare' },
  { id: '659', label: 'Miljöchef' },
  { id: '660', label: 'Miljöhandläggare' },
  { id: '661', label: 'Miljöingenjör' },
  { id: '662', label: 'Miljökonsult' },
  { id: '663', label: 'Miljökoordinator' },
  { id: '664', label: 'Miljöplanerare' },
  { id: '665', label: 'Miljösamordnare' },
  { id: '666', label: 'Miljötekniker' },
  { id: '667', label: 'Naturbevakare' },
  { id: '668', label: 'Naturvårdsarbetare' },
  { id: '669', label: 'Naturvårdschef' },
  { id: '670', label: 'Odlingstekniker' },
  { id: '671', label: 'Parkeringsvakt' },
  { id: '672', label: 'Pälsodlare' },
  { id: '673', label: 'Renare' },
  { id: '674', label: 'Renhållningsarbetare' },
  { id: '675', label: 'Renhållningschef' },
  { id: '676', label: 'Rengöringsmedelstillverkare' },
  { id: '677', label: 'Ridinstruktör' },
  { id: '678', label: 'Skogsarbetare' },
  { id: '679', label: 'Skogsförvaltare' },
  { id: '680', label: 'Skogsinspektör' },
  { id: '681', label: 'Skogsmaskinförare' },
  { id: '682', label: 'Skogsplanerare' },
  { id: '683', label: 'Skogstekniker' },
  { id: '684', label: 'Solcellsmontör' },
  { id: '685', label: 'Sophämtare' },
  { id: '686', label: 'Sotare' },
  { id: '687', label: 'Trädgårdsanläggare' },
  { id: '688', label: 'Trädgårdsarbetare' },
  { id: '689', label: 'Trädgårdsmästare' },
  { id: '690', label: 'Vattenförvaltare' },
  { id: '691', label: 'Vattenprovtagare' },
  { id: '692', label: 'Vindkraftstekniker' },
  { id: '693', label: 'Viltvårdare' },
  { id: '694', label: 'Återvinningsarbetare' },

  // Sjöfart & Fartyg
  { id: '695', label: 'Befälhavare' },
  { id: '696', label: 'Däcksman' },
  { id: '697', label: 'Fartygsbefäl' },
  { id: '698', label: 'Fartygschaufför' },
  { id: '699', label: 'Fartygskock' },
  { id: '700', label: 'Fartygsmekaniker' },
  { id: '701', label: 'Fiskare' },
  { id: '702', label: 'Havskapten' },
  { id: '703', label: 'Lots' },
  { id: '704', label: 'Matros' },
  { id: '705', label: 'Motorman' },
  { id: '706', label: 'Sjöbefäl' },
  { id: '707', label: 'Sjökapt' },
  { id: '708', label: 'Sjöman' },
  { id: '709', label: 'Styrman' },

  // Detaljhandel & Butik
  { id: '710', label: 'Apotekare' },
  { id: '711', label: 'Apoteksassistent' },
  { id: '712', label: 'Apotekschef' },
  { id: '713', label: 'Apotekstekniker' },
  { id: '714', label: 'Apoteksbiträde' },
  { id: '715', label: 'Bensinstationsföreståndare' },
  { id: '716', label: 'Bilförsäljare' },
  { id: '717', label: 'Bilmekaniker' },
  { id: '718', label: 'Bilplåtslagare' },
  { id: '719', label: 'Bilsadelmakare' },
  { id: '720', label: 'Bilverkstadsägare' },
  { id: '721', label: 'Blomsterhandlare' },
  { id: '722', label: 'Bokhandlare' },
  { id: '723', label: 'Brevbärare' },
  { id: '724', label: 'Byggvaruhandlare' },
  { id: '725', label: 'Charkuterist' },
  { id: '726', label: 'Cykelhandlare' },
  { id: '727', label: 'Cykelmekaniker' },
  { id: '728', label: 'Däckmontör' },
  { id: '729', label: 'Däcktekniker' },
  { id: '730', label: 'Elektronikhandlare' },
  { id: '731', label: 'Elektronikreparatör' },
  { id: '732', label: 'Elhandlare' },
  { id: '733', label: 'Färghandlare' },
  { id: '734', label: 'Fiskhandlare' },
  { id: '735', label: 'Florist' },
  { id: '736', label: 'Försäkringsagent' },
  { id: '737', label: 'Försäkringsförmedlare' },
  { id: '738', label: 'Glasögonoptiker' },
  { id: '739', label: 'Glasögonreparatör' },
  { id: '740', label: 'Guldsmed' },
  { id: '741', label: 'Hemelektronikförsäljare' },
  { id: '742', label: 'Hobbyhandlare' },
  { id: '743', label: 'Husgerådshandlare' },
  { id: '744', label: 'Inredare' },
  { id: '745', label: 'Inredningskonsult' },
  { id: '746', label: 'Juvelerare' },
  { id: '747', label: 'Kassabiträde' },
  { id: '748', label: 'Kassör' },
  { id: '749', label: 'Kioskägare' },
  { id: '750', label: 'Konfektyrhandlare' },
  { id: '751', label: 'Körsbärsodlare' },
  { id: '752', label: 'Köttbörsäljare' },
  { id: '753', label: 'Kött handlare' },
  { id: '754', label: 'Leksakshandlare' },
  { id: '755', label: 'Livsmedelshandlare' },
  { id: '756', label: 'Ljudbokuppläsare' },
  { id: '757', label: 'Måleriföretagare' },
  { id: '758', label: 'Maskinhandlare' },
  { id: '759', label: 'Materialförsäljare' },
  { id: '760', label: 'Mediaförsäljare' },
  { id: '761', label: 'Modekonsult' },
  { id: '762', label: 'Möbelhandlare' },
  { id: '763', label: 'Möbeltapetserare' },
  { id: '764', label: 'Optiker' },
  { id: '765', label: 'Optikerassistent' },
  { id: '766', label: 'Pappershandlare' },
  { id: '767', label: 'Partihandlare' },
  { id: '768', label: 'Plockare' },
  { id: '769', label: 'Presenthandlare' },
  { id: '770', label: 'Reklambladsutdelare' },
  { id: '771', label: 'Reservdelsförsäljare' },
  { id: '772', label: 'Servicehandlare' },
  { id: '773', label: 'Skoaffärsägare' },
  { id: '774', label: 'Skomakare' },
  { id: '775', label: 'Skönhets konsulent' },
  { id: '776', label: 'Slaktare' },
  { id: '777', label: 'Sportaffärsägare' },
  { id: '778', label: 'Stenugnsbageriägare' },
  { id: '779', label: 'Säljare hemelektronik' },
  { id: '780', label: 'Säljare möbler' },
  { id: '781', label: 'Textilhandlare' },
  { id: '782', label: 'Tidningsbud' },
  { id: '783', label: 'Tobakshandlare' },
  { id: '784', label: 'Trädgårdshandlare' },
  { id: '785', label: 'Urmakare' },
  { id: '786', label: 'Vakt master' },
  { id: '787', label: 'Vapenhandlare' },
  { id: '788', label: 'Varuhuschef' },
  { id: '789', label: 'Vävnadsförsäljare' },
  { id: '790', label: 'Växt handlare' },
  { id: '791', label: 'Watchexpert' },

  // Hemtjänst & Personlig service
  { id: '792', label: 'Barnflicka' },
  { id: '793', label: 'Barnvakt' },
  { id: '794', label: 'Behandlingsassistent' },
  { id: '795', label: 'Behandlingspedagog' },
  { id: '796', label: 'Behörig fotterapeut' },
  { id: '797', label: 'Behörig massör' },
  { id: '798', label: 'Begravningsentreprenör' },
  { id: '799', label: 'Begravningsrådgivare' },
  { id: '800', label: 'Bilrekond' },
  { id: '801', label: 'Bilvårdare' },
  { id: '802', label: 'Bostadshandlare' },
  { id: '803', label: 'Coach' },
  { id: '804', label: 'Dietist' },
  { id: '805', label: 'Doula' },
  { id: '806', label: 'Familjehem' },
  { id: '807', label: 'Familjerådgivare' },
  { id: '808', label: 'Fotvårdare' },
  { id: '809', label: 'Frisör' },
  { id: '810', label: 'Frisör elev' },
  { id: '811', label: 'Friskvårdskonsult' },
  { id: '812', label: 'Gravöppnare' },
  { id: '813', label: 'Grillkock' },
  { id: '814', label: 'Hemtjänstassistent' },
  { id: '815', label: 'Hemtjänstpersonal' },
  { id: '816', label: 'Hudterapeut' },
  { id: '817', label: 'Kiropraktor' },
  { id: '818', label: 'Kostnadsrevisor' },
  { id: '819', label: 'Kroppsbehandlare' },
  { id: '820', label: 'Kryddsterapeut' },
  { id: '821', label: 'Livcoach' },
  { id: '822', label: 'Livsstilscoach' },
  { id: '823', label: 'Makeupartist' },
  { id: '824', label: 'Massageterapeut' },
  { id: '825', label: 'Massör' },
  { id: '826', label: 'Nagelterapeut' },
  { id: '827', label: 'Naprapat' },
  { id: '828', label: 'Personlig assistent' },
  { id: '829', label: 'Personlig tränare' },
  { id: '830', label: 'Receptarie' },
  { id: '831', label: 'Rörmokarassistent' },
  { id: '832', label: 'Samtalsterapeut' },
  { id: '833', label: 'Sexolog' },
  { id: '834', label: 'Skönhetsterapeut' },
  { id: '835', label: 'Spaterapeut' },
  { id: '836', label: 'Tatueringsterapeut' },
  { id: '837', label: 'Tatuör' },
  { id: '838', label: 'Terapeut' },
  { id: '839', label: 'Yogalärare' },
  { id: '840', label: 'Yogaterapeut' },

  // Nya Teknologier & Digitala Yrken
  { id: '841', label: 'AI-etiker' },
  { id: '842', label: 'AI-specialist' },
  { id: '843', label: 'AI-tränare' },
  { id: '844', label: 'Blockchain-utvecklare' },
  { id: '845', label: 'Chatbot-utvecklare' },
  { id: '846', label: 'Cloud-arkitekt' },
  { id: '847', label: 'Cloud-specialist' },
  { id: '848', label: 'Community manager' },
  { id: '849', label: 'Cryptovaluta-handlare' },
  { id: '850', label: 'Cybersecurity-analytiker' },
  { id: '851', label: 'Data visualization specialist' },
  { id: '852', label: 'Dataskyddsombud' },
  { id: '853', label: 'Digital analytiker' },
  { id: '854', label: 'Digital designer' },
  { id: '855', label: 'Digital marknadsförare' },
  { id: '856', label: 'Digital strateg' },
  { id: '857', label: 'E-handelsspecialist' },
  { id: '858', label: 'E-sport coach' },
  { id: '859', label: 'E-sport spelare' },
  { id: '860', label: 'E-sport tävlingsledare' },
  { id: '861', label: 'Game designer' },
  { id: '862', label: 'Game master' },
  { id: '863', label: 'Game tester' },
  { id: '864', label: 'Gaming streamer' },
  { id: '865', label: 'Growth hacker' },
  { id: '866', label: 'Influencer' },
  { id: '867', label: 'Internetmarknadsförare' },
  { id: '868', label: 'IT-forensiker' },
  { id: '869', label: 'IT-säkerhetsspecialist' },
  { id: '870', label: 'Machine learning engineer' },
  { id: '871', label: 'NFT-konstnär' },
  { id: '872', label: 'Prompt engineer' },
  { id: '873', label: 'Robotics engineer' },
  { id: '874', label: 'Search engine optimizer' },
  { id: '875', label: 'Smart contract utvecklare' },
  { id: '876', label: 'Social media analytiker' },
  { id: '877', label: 'Virtual reality designer' },
  { id: '878', label: 'Web analyst' },
  { id: '879', label: 'Webmaster' },

  // Gig-ekonomi & Frilans
  { id: '880', label: 'Biljettkontrollant' },
  { id: '881', label: 'Bud' },
  { id: '882', label: 'Cykelbud' },
  { id: '883', label: 'Dog walker' },
  { id: '884', label: 'Food delivery förare' },
  { id: '885', label: 'Frilansjournalist' },
  { id: '886', label: 'Frilanskock' },
  { id: '887', label: 'Frilansöversättare' },
  { id: '888', label: 'House sitter' },
  { id: '889', label: 'Matkassekompilator' },
  { id: '890', label: 'Mystery shopper' },
  { id: '891', label: 'Online tutor' },
  { id: '892', label: 'Parkeringsvakt' },
  { id: '893', label: 'Plattformsförare' },
  { id: '894', label: 'Prova-på-dag-föreläsare' },
  { id: '895', label: 'Rider' },
  { id: '896', label: 'Samåkningsförare' },
  { id: '897', label: 'Säsongsarbetare' },
  { id: '898', label: 'Stödassistent' },
  { id: '899', label: 'Stödpedagog' },
  { id: '900', label: 'Task runner' },
  { id: '901', label: 'Uber förare' },

  // Specialiserade Hantverkare
  { id: '902', label: 'Båtbyggare' },
  { id: '903', label: 'Båtmekaniker' },
  { id: '904', label: 'Bokbindare' },
  { id: '905', label: 'Bordtennisreparatör' },
  { id: '906', label: 'Bromsspecialist' },
  { id: '907', label: 'Bågskytt' },
  { id: '908', label: 'Cad-ritare' },
  { id: '909', label: 'Cnc-tekniker' },
  { id: '910', label: 'Dekoratör' },
  { id: '911', label: 'Dekorationsmålare' },
  { id: '912', label: 'Diamantslipare' },
  { id: '913', label: 'Dockmakare' },
  { id: '914', label: 'Dörrmontör' },
  { id: '915', label: 'Elbilsmekaniker' },
  { id: '916', label: 'Elskåpsmontör' },
  { id: '917', label: 'Emballagetekniker' },
  { id: '918', label: 'Energiexpert' },
  { id: '919', label: 'Fasadrenoverare' },
  { id: '920', label: 'Finsnickare' },
  { id: '921', label: 'Fönsterbyggare' },
  { id: '922', label: 'Fönsterrenoverare' },
  { id: '923', label: 'Garageportmontör' },
  { id: '924', label: 'Glasmästare' },
  { id: '925', label: 'Hissreparatör' },
  { id: '926', label: 'Hissmontör' },
  { id: '927', label: 'Högtryckstvättare' },
  { id: '928', label: 'Inbrottsskyddsmontör' },
  { id: '929', label: 'Kakelugnsmakare' },
  { id: '930', label: 'Kakelsättare' },
  { id: '931', label: 'Kastanjeröstare' },
  { id: '932', label: 'Klädselmakare' },
  { id: '933', label: 'Köksmontör' },
  { id: '934', label: 'Larmtekniker' },
  { id: '935', label: 'Larminstallatör' },
  { id: '936', label: 'Låssmed' },
  { id: '937', label: 'Marinmekaniker' },
  { id: '938', label: 'Medaljmakare' },
  { id: '939', label: 'Mediamagneter' },
  { id: '940', label: 'Modellbyggare' },
  { id: '941', label: 'Mopederparatör' },
  { id: '942', label: 'Mopedmekaniker' },
  { id: '943', label: 'Motorcykelmekaniker' },
  { id: '944', label: 'Munblåsare' },
  { id: '945', label: 'Murare' },
  { id: '946', label: 'Möbelrenoverare' },
  { id: '947', label: 'Mönsterkonstruktör' },
  { id: '948', label: 'Prototyptillverkare' },
  { id: '949', label: 'Radiatorrenoverare' },
  { id: '950', label: 'Rambindare' },
  { id: '951', label: 'Renoveringsarbetare' },
  { id: '952', label: 'Restaurerare' },
  { id: '953', label: 'Rostskyddsmålare' },
  { id: '954', label: 'Sadelmakare' },
  { id: '955', label: 'Säkerhetsglasinstallatör' },
  { id: '956', label: 'Solfilmsmontör' },
  { id: '957', label: 'Sotare' },
  { id: '958', label: 'Spisinstallatör' },
  { id: '959', label: 'Stenarbetare' },
  { id: '960', label: 'Stenhuggare' },
  { id: '961', label: 'Symaskinsreparatör' },
  { id: '962', label: 'Tapetserare' },
  { id: '963', label: 'Terrassbyggare' },
  { id: '964', label: 'Textilrenoverare' },
  { id: '965', label: 'Trapprenoverare' },
  { id: '966', label: 'Ugnstekniker' },
  { id: '967', label: 'Upholsterer' },
  { id: '968', label: 'Vapensmed' },
  { id: '969', label: 'Varvsarbetare' },
  { id: '970', label: 'Vasblåsare' },
  { id: '971', label: 'Verktygsmakare' },
  { id: '972', label: 'Vindskyddsmontör' },
  { id: '973', label: 'Vinylmontör' },

  // Offentlig Sektor & Ideellt
  { id: '974', label: 'Ambassadpersonal' },
  { id: '975', label: 'Arbetsförmedlare' },
  { id: '976', label: 'Biståndsarbetare' },
  { id: '977', label: 'Biståndshandläggare' },
  { id: '978', label: 'Civilsamhällesarbetare' },
  { id: '979', label: 'Demokratikonsulent' },
  { id: '980', label: 'Diplomat' },
  { id: '981', label: 'Diakon' },
  { id: '982', label: 'Domare' },
  { id: '983', label: 'Domstolsföreståndare' },
  { id: '984', label: 'Domstolshandläggare' },
  { id: '985', label: 'Domstolsnotarie' },
  { id: '986', label: 'Domstolssekreterare' },
  { id: '987', label: 'Flyktinghandläggare' },
  { id: '988', label: 'Folkhögskolelärare' },
  { id: '989', label: 'Fredsarbetare' },
  { id: '990', label: 'Frivilligarbetare' },
  { id: '991', label: 'Församlingspedagog' },
  { id: '992', label: 'Gränspolis' },
  { id: '993', label: 'Hemlöshetshandläggare' },
  { id: '994', label: 'Ideell arbetskraft' },
  { id: '995', label: 'Integrationsarbetare' },
  { id: '996', label: 'Integrationshandläggare' },
  { id: '997', label: 'Kommunikationschef' },
  { id: '998', label: 'Kommunikatör' },
  { id: '999', label: 'Kommunalråd' },
  { id: '1000', label: 'Krigsmaterielinspektör' },
];

