import type { AutocompleteOption } from '@/components/common/Autocomplete';

// Common occupations for dropdowns in Career components
export const COMMON_OCCUPATIONS: AutocompleteOption[] = [
  { id: '1', label: 'Administratör' },
  { id: '2', label: 'Controller' },
  { id: '3', label: 'Ekonomiassistent' },
  { id: '4', label: 'Ekonom' },
  { id: '5', label: 'HR-assistent' },
  { id: '6', label: 'HR-specialist' },
  { id: '7', label: 'Inköpare' },
  { id: '8', label: 'Kundtjänstmedarbetare' },
  { id: '9', label: 'Lagerarbetare' },
  { id: '10', label: 'Marknadsassistent' },
  { id: '11', label: 'Marknadschef' },
  { id: '12', label: 'Projektledare' },
  { id: '13', label: 'Receptionist' },
  { id: '14', label: 'Redovisningskonsult' },
  { id: '15', label: 'Säljare' },
  { id: '16', label: 'Säljchef' },
  { id: '17', label: 'Systemutvecklare' },
  { id: '18', label: 'IT-tekniker' },
  { id: '19', label: 'Nätverkstekniker' },
  { id: '20', label: 'Supporttekniker' },
  { id: '21', label: 'Webbutvecklare' },
  { id: '22', label: 'Frontendutvecklare' },
  { id: '23', label: 'Backendutvecklare' },
  { id: '24', label: 'Fullstackutvecklare' },
  { id: '25', label: 'Tech Lead' },
  { id: '26', label: 'UX-designer' },
  { id: '27', label: 'UI-designer' },
  { id: '28', label: 'Produktägare' },
  { id: '29', label: 'Scrum Master' },
  { id: '30', label: 'Dataanalytiker' },
  { id: '31', label: 'Lärare' },
  { id: '32', label: 'Förskollärare' },
  { id: '33', label: 'Specialpedagog' },
  { id: '34', label: 'Sjuksköterska' },
  { id: '35', label: 'Undersköterska' },
  { id: '36', label: 'Läkare' },
  { id: '37', label: 'Sjukgymnast' },
  { id: '38', label: 'Arbetsterapeut' },
  { id: '39', label: 'Psykolog' },
  { id: '40', label: 'Kurator' },
  { id: '41', label: 'Socialsekreterare' },
  { id: '42', label: 'Personlig assistent' },
  { id: '43', label: 'Vårdbiträde' },
  { id: '44', label: 'Vårdenhetschef' },
  { id: '45', label: 'Byggarbetare' },
  { id: '46', label: 'Elektriker' },
  { id: '47', label: 'Rörmokare' },
  { id: '48', label: 'Snickare' },
  { id: '49', label: 'Målare' },
  { id: '50', label: 'Fastighetsskötare' },
  { id: '51', label: 'Truckförare' },
  { id: '52', label: 'Chaufför' },
  { id: '53', label: 'Servicetekniker' },
  { id: '54', label: 'Maskinförare' },
  { id: '55', label: 'Kock' },
  { id: '56', label: 'Servitris' },
  { id: '57', label: 'Barista' },
  { id: '58', label: 'Hotellreceptionist' },
  { id: '59', label: 'Städare' },
  { id: '60', label: 'Vaktmästare' },
  { id: '61', label: 'Butikssäljare' },
  { id: '62', label: 'Butikschef' },
  { id: '63', label: 'Visuell merchandiser' },
  { id: '64', label: 'Lagerchef' },
  { id: '65', label: 'Logistiker' },
  { id: '66', label: 'Transportplanerare' },
  { id: '67', label: 'Tulldeklarant' },
  { id: '68', label: 'Jurist' },
  { id: '69', label: 'Advokat' },
  { id: '70', label: 'Notarie' },
  { id: '71', label: 'Polis' },
  { id: '72', label: 'Väktare' },
  { id: '73', label: 'Ordningsvakt' },
  { id: '74', label: 'Brandman' },
  { id: '75', label: 'Journalist' },
  { id: '76', label: 'Copywriter' },
  { id: '77', label: 'Översättare' },
  { id: '78', label: 'Grafisk designer' },
  { id: '79', label: 'Fotograf' },
  { id: '80', label: 'Videoredigerare' },
  { id: '81', label: 'Ingenjör' },
  { id: '82', label: 'Civilingenjör' },
  { id: '83', label: 'Arkitekt' },
  { id: '84', label: 'Kvalitetstekniker' },
  { id: '85', label: 'Produktionstekniker' },
  { id: '86', label: 'Drifttekniker' },
  { id: '87', label: 'Fastighetsmäklare' },
  { id: '88', label: 'Försäljningschef' },
  { id: '89', label: 'Verkställande direktör' },
  { id: '90', label: 'Managementkonsult' },
];
