import type { AutocompleteOption } from '@/components/common/Autocomplete';

// Comprehensive list of common occupations in Sweden
export const COMMON_OCCUPATIONS: AutocompleteOption[] = [
  // Administration & Kontor
  { id: '1', label: 'Administratör' },
  { id: '2', label: 'Administrativ chef' },
  { id: '3', label: 'Assistent' },
  { id: '4', label: 'Chefsekretetare' },
  { id: '5', label: 'Controller' },
  { id: '6', label: 'Dokumentcontroller' },
  { id: '7', label: 'Ekonomiassistent' },
  { id: '8', label: 'Ekonom' },
  { id: '9', label: 'Ekonomichef' },
  { id: '10', label: 'HR-administratör' },
  { id: '11', label: 'HR-assistent' },
  { id: '12', label: 'HR-specialist' },
  { id: '13', label: 'HR-chef' },
  { id: '14', label: 'Inköpare' },
  { id: '15', label: 'Inköpschef' },
  { id: '16', label: 'Kanslichef' },
  { id: '17', label: 'Kassör' },
  { id: '18', label: 'Kontorschef' },
  { id: '19', label: 'Löneadministratör' },
  { id: '20', label: 'Lönekonsult' },
  { id: '21', label: 'Office manager' },
  { id: '22', label: 'Projektadministratör' },
  { id: '23', label: 'Projektkoordinator' },
  { id: '24', label: 'Receptionist' },
  { id: '25', label: 'Redovisningsassistent' },
  { id: '26', label: 'Redovisningskonsult' },
  { id: '27', label: 'Redovisningsekonom' },
  { id: '28', label: 'Sekreterare' },
  { id: '29', label: 'Verksamhetscontroller' },
  { id: '30', label: 'Verksamhetsutvecklare' },

  // Försäljning & Marknad
  { id: '31', label: 'Account manager' },
  { id: '32', label: 'Affärsutvecklare' },
  { id: '33', label: 'Butikschef' },
  { id: '34', label: 'Butikssäljare' },
  { id: '35', label: 'Category manager' },
  { id: '36', label: 'Channel manager' },
  { id: '37', label: 'Customer success manager' },
  { id: '38', label: 'Försäljningschef' },
  { id: '39', label: 'Försäljningsdirektör' },
  { id: '40', label: 'Försäljningsingenjör' },
  { id: '41', label: 'Försäljningskonsult' },
  { id: '42', label: 'Försäljningskoordinator' },
  { id: '43', label: 'Key account manager' },
  { id: '44', label: 'Kundansvarig' },
  { id: '45', label: 'Kundbefattningshavare' },
  { id: '46', label: 'Kundtjänstchef' },
  { id: '47', label: 'Kundtjänstmedarbetare' },
  { id: '48', label: 'Marknadsanalytiker' },
  { id: '49', label: 'Marknadsassistent' },
  { id: '50', label: 'Marknadschef' },
  { id: '51', label: 'Marknadskoordinator' },
  { id: '52', label: 'Marknadskommunikatör' },
  { id: '53', label: 'Mediasäljare' },
  { id: '54', label: 'Produktspecialist' },
  { id: '55', label: 'Regionchef' },
  { id: '56', label: 'Relationsansvarig' },
  { id: '57', label: 'Säljare' },
  { id: '58', label: 'Säljassistent' },
  { id: '59', label: 'Säljchef' },
  { id: '60', label: 'Säljkoordinator' },
  { id: '61', label: 'Säljledare' },
  { id: '62', label: 'Säljprojektledare' },
  { id: '63', label: 'Säljregionschef' },
  { id: '64', label: 'Säljrepresentant' },
  { id: '65', label: 'Telefonförsäljare' },
  { id: '66', label: 'Visuell merchandiser' },

  // IT & Teknik
  { id: '67', label: 'Apputvecklare' },
  { id: '68', label: 'Backendutvecklare' },
  { id: '69', label: 'BI-utvecklare' },
  { id: '70', label: 'Business analyst' },
  { id: '71', label: 'Chief technology officer' },
  { id: '72', label: 'Cloud engineer' },
  { id: '73', label: 'Data engineer' },
  { id: '74', label: 'Dataanalytiker' },
  { id: '75', label: 'Datascientist' },
  { id: '76', label: 'DevOps engineer' },
  { id: '77', label: 'Frontendutvecklare' },
  { id: '78', label: 'Fullstackutvecklare' },
  { id: '79', label: 'GIS-utvecklare' },
  { id: '80', label: 'Helpdesktekniker' },
  { id: '81', label: 'IT-arkitekt' },
  { id: '82', label: 'IT-chef' },
  { id: '83', label: 'IT-drifttekniker' },
  { id: '84', label: 'IT-koordinator' },
  { id: '85', label: 'IT-projektledare' },
  { id: '86', label: 'IT-säkerhetsansvarig' },
  { id: '87', label: 'IT-tekniker' },
  { id: '88', label: 'Javautvecklare' },
  { id: '89', label: 'Mjukvaruarkitekt' },
  { id: '90', label: 'Mjukvaruutvecklare' },
  { id: '91', label: 'Nätverksadministratör' },
  { id: '92', label: 'Nätverkstekniker' },
  { id: '93', label: 'PHP-utvecklare' },
  { id: '94', label: 'Produktägare' },
  { id: '95', label: 'Pythonutvecklare' },
  { id: '96', label: 'QA-engineer' },
  { id: '97', label: 'Reactutvecklare' },
  { id: '98', label: 'Release manager' },
  { id: '99', label: 'Scrum master' },
  { id: '100', label: 'Servicedeskmedarbetare' },
  { id: '101', label: 'Site reliability engineer' },
  { id: '102', label: 'Supporttekniker' },
  { id: '103', label: 'Systemadministratör' },
  { id: '104', label: 'Systemanalytiker' },
  { id: '105', label: 'Systemarkitekt' },
  { id: '106', label: 'Systemutvecklare' },
  { id: '107', label: 'Systemförvaltare' },
  { id: '108', label: 'Systemtestare' },
  { id: '109', label: 'Tech lead' },
  { id: '110', label: 'Testautomatiserare' },
  { id: '111', label: 'Testare' },
  { id: '112', label: 'Testledare' },
  { id: '113', label: 'UI-designer' },
  { id: '114', label: 'UX-designer' },
  { id: '115', label: 'UX-researcher' },
  { id: '116', label: 'Webbdesigner' },
  { id: '117', label: 'Webbutvecklare' },

  // Vård & Hälsa
  { id: '118', label: 'Ambulanssjukvårdare' },
  { id: '119', label: 'Anestesisjuksköterska' },
  { id: '120', label: 'Arbetsterapeut' },
  { id: '121', label: 'Audionom' },
  { id: '122', label: 'Barnmorska' },
  { id: '123', label: 'Barnsjuksköterska' },
  { id: '124', label: 'Behandlingsassistent' },
  { id: '125', label: 'Beteendevetare' },
  { id: '126', label: 'Biomedicinsk analytiker' },
  { id: '127', label: 'Dietist' },
  { id: '128', label: 'Distriktssköterska' },
  { id: '129', label: 'Fysioterapeut' },
  { id: '130', label: 'Habiliteringsassistent' },
  { id: '131', label: 'Hemtjänstassistent' },
  { id: '132', label: 'Hjälpmedelstekniker' },
  { id: '133', label: 'Intensivvårdssjuksköterska' },
  { id: '134', label: 'Kurator' },
  { id: '135', label: 'Läkare' },
  { id: '136', label: 'Läkarsekreterare' },
  { id: '137', label: 'Medicinsk sekreterare' },
  { id: '138', label: 'Mentalvårdare' },
  { id: '139', label: 'Operationssjuksköterska' },
  { id: '140', label: 'Optiker' },
  { id: '141', label: 'Personlig assistent' },
  { id: '142', label: 'Psykolog' },
  { id: '143', label: 'Psykoterapeut' },
  { id: '144', label: 'Receptionist vårdcentral' },
  { id: '145', label: 'Röntgensjuksköterska' },
  { id: '146', label: 'Sjukgymnast' },
  { id: '147', label: 'Sjuksköterska' },
  { id: '148', label: 'Skolsköterska' },
  { id: '149', label: 'Socionom' },
  { id: '150', label: ' specialistsjuksköterska' },
  { id: '151', label: 'Tandhygienist' },
  { id: '152', label: 'Tandsköterska' },
  { id: '153', label: 'Tandtekniker' },
  { id: '154', label: 'Undersköterska' },
  { id: '155', label: 'Vårdadministratör' },
  { id: '156', label: 'Vårdbiträde' },
  { id: '157', label: 'Vårdenhetschef' },
  { id: '158', label: 'Vårdledare' },
  { id: '159', label: 'Vårdpedagog' },

  // Utbildning
  { id: '160', label: 'Biträdande rektor' },
  { id: '161', label: 'Barnskötare' },
  { id: '162', label: 'Elevassistent' },
  { id: '163', label: 'Förskolechef' },
  { id: '164', label: 'Förskollärare' },
  { id: '165', label: 'Fritidspedagog' },
  { id: '166', label: 'Grundskollärare' },
  { id: '167', label: 'Gymnasielärare' },
  { id: '168', label: 'Kursadministratör' },
  { id: '169', label: 'Lärare' },
  { id: '170', label: 'Lärarvikarie' },
  { id: '171', label: 'Modersmålslärare' },
  { id: '172', label: 'Rektor' },
  { id: '173', label: 'Skoladministratör' },
  { id: '174', label: 'Skolbibliotekarie' },
  { id: '175', label: 'Skolsköterska' },
  { id: '176', label: 'Skolskötare' },
  { id: '177', label: 'Specialpedagog' },
  { id: '178', label: 'Speciallärare' },
  { id: '179', label: 'Studie- och yrkesvägledare' },
  { id: '180', label: 'Studievägledare' },
  { id: '181', label: 'Utbildare' },
  { id: '182', label: 'Utbildningsadministratör' },
  { id: '183', label: 'Utbildningsansvarig' },
  { id: '184', label: 'Utbildningschef' },
  { id: '185', label: 'Utbildningskoordinator' },
  { id: '186', label: 'Utbildningsledare' },
  { id: '187', label: 'Vikarierande lärare' },

  // Bygg & Anläggning
  { id: '188', label: 'Anläggningsarbetare' },
  { id: '189', label: 'Anläggningsingenjör' },
  { id: '190', label: 'Arbetsledare bygg' },
  { id: '191', label: 'Betongarbetare' },
  { id: '192', label: 'Betongare' },
  { id: '193', label: 'Bilmekaniker' },
  { id: '194', label: 'Byggarbetare' },
  { id: '195', label: 'Byggchefsingenjör' },
  { id: '196', label: 'Byggnadsmålare' },
  { id: '197', label: 'Byggnadsarbetare' },
  { id: '198', label: 'Byggnadsingenjör' },
  { id: '199', label: 'Byggnadsplåtslagare' },
  { id: '200', label: 'Byggnadsritare' },
  { id: '201', label: 'Byggnadssnickare' },
  { id: '202', label: 'Byggnadstekniker' },
  { id: '203', label: 'Driftchef fastighet' },
  { id: '204', label: 'Elektriker' },
  { id: '205', label: 'Fastighetsingenjör' },
  { id: '206', label: 'Fastighetsmäklare' },
  { id: '207', label: 'Fastighetsskötare' },
  { id: '208', label: 'Fastighetstekniker' },
  { id: '209', label: 'Fastighetsvärderare' },
  { id: '210', label: 'Fordonsmekaniker' },
  { id: '211', label: 'Golvläggare' },
  { id: '212', label: 'Hantverkare' },
  { id: '213', label: 'Industrisnickare' },
  { id: '214', label: 'Isoleringsmontör' },
  { id: '215', label: 'Kranförare' },
  { id: '216', label: 'Kylmontör' },
  { id: '217', label: 'Källarmästare' },
  { id: '218', label: 'Mekaniker' },
  { id: '219', label: 'Montör' },
  { id: '220', label: 'Målare' },
  { id: '221', label: 'Plåtslagare' },
  { id: '222', label: 'Projekteringsledare' },
  { id: '223', label: 'Projektledare bygg' },
  { id: '224', label: 'Platschef' },
  { id: '225', label: 'Rivningsarbetare' },
  { id: '226', label: 'Rörmokare' },
  { id: '227', label: 'Servicetekniker' },
  { id: '228', label: 'Skadesanerare' },
  { id: '229', label: 'Snickare' },
  { id: '230', label: 'Ställningsbyggare' },
  { id: '231', label: 'Svetsare' },
  { id: '232', label: 'Takmontör' },
  { id: '233', label: 'Truckförare' },
  { id: '234', label: 'Ventilationsmontör' },
  { id: '235', label: 'Ventilationstekniker' },
  { id: '236', label: 'Vvs-montör' },
  { id: '237', label: 'Vvs-tekniker' },

  // Industri & Produktion
  { id: '238', label: 'Arbetsledare industri' },
  { id: '239', label: 'Arbetare' },
  { id: '240', label: 'Bandsågare' },
  { id: '241', label: 'CNC-operatör' },
  { id: '242', label: 'Driftchef' },
  { id: '243', label: 'Driftledare' },
  { id: '244', label: 'Drifttekniker' },
  { id: '245', label: 'Fabriksarbetare' },
  { id: '246', label: 'Förbandsarbetare' },
  { id: '247', label: 'Industriarbetare' },
  { id: '248', label: 'Industrielektriker' },
  { id: '249', label: 'Industrirengöring' },
  { id: '250', label: 'Kemist' },
  { id: '251', label: 'Kvalitetsansvarig' },
  { id: '252', label: 'Kvalitetschef' },
  { id: '253', label: 'Kvalitetsingenjör' },
  { id: '254', label: 'Kvalitetstekniker' },
  { id: '255', label: 'Laborant' },
  { id: '256', label: 'Lackerare' },
  { id: '257', label: 'Lagerarbetare' },
  { id: '258', label: 'Lagerchef' },
  { id: '259', label: 'Logistikansvarig' },
  { id: '260', label: 'Logistikchef' },
  { id: '261', label: 'Logistiker' },
  { id: '262', label: 'Logistikkoordinator' },
  { id: '263', label: 'Maskinbefäl' },
  { id: '264', label: 'Maskinförare' },
  { id: '265', label: 'Maskinoperatör' },
  { id: '266', label: 'Maskinreparatör' },
  { id: '267', label: 'Maskinsetter' },
  { id: '268', label: 'Materialplanerare' },
  { id: '269', label: 'Mekaniker' },
  { id: '270', label: 'Packare' },
  { id: '271', label: 'Processoperatör' },
  { id: '272', label: 'Produktionsarbetare' },
  { id: '273', label: 'Produktionschef' },
  { id: '274', label: 'Produktionsingenjör' },
  { id: '275', label: 'Produktionsledare' },
  { id: '276', label: 'Produktionsplanerare' },
  { id: '277', label: 'Produktionstekniker' },
  { id: '278', label: 'Skiftledare' },
  { id: '279', label: 'Supply chain manager' },
  { id: '280', label: 'Transportledare' },
  { id: '281', label: 'Transportplanerare' },
  { id: '282', label: 'Tulldeklarant' },
  { id: '283', label: 'Underhållsansvarig' },
  { id: '284', label: 'Underhållschef' },
  { id: '285', label: 'Underhållsledare' },
  { id: '286', label: 'Underhållstekniker' },
  { id: '287', label: 'Verkstadsarbetare' },
  { id: '288', label: 'Verkstadsingenjör' },
  { id: '289', label: 'Verkmästare' },

  // Transport & Logistik
  { id: '290', label: 'Bilförare' },
  { id: '291', label: 'Budbilsförare' },
  { id: '292', label: 'Buschaufför' },
  { id: '293', label: 'Chaufför' },
  { id: '294', label: 'Distributionselektriker' },
  { id: '295', label: 'Distributionsförare' },
  { id: '296', label: 'Fjärrförare' },
  { id: '297', label: 'Färjelots' },
  { id: '298', label: 'Godshanterare' },
  { id: '299', label: 'Kranförare' },
  { id: '300', label: 'Lastbilschaufför' },
  { id: '301', label: 'Lastbilsförare' },
  { id: '302', label: 'Linjechaufför' },
  { id: '303', label: 'Lokalvårdare' },
  { id: '304', label: 'Pilot' },
  { id: '305', label: 'Speditör' },
  { id: '306', label: 'Stuveriarbetare' },
  { id: '307', label: 'Taxiförare' },
  { id: '308', label: 'Trafikledare' },
  { id: '309', label: 'Truckförare' },
  { id: '310', label: 'Åkerichef' },

  // Hotell & Restaurang
  { id: '311', label: 'Bagare' },
  { id: '312', label: 'Barista' },
  { id: '313', label: 'Bartender' },
  { id: '314', label: 'Buffévärdinna' },
  { id: '315', label: 'Cafébiträde' },
  { id: '316', label: 'Cateringansvarig' },
  { id: '317', label: 'Conferencier' },
  { id: '318', label: 'Diskare' },
  { id: '319', label: 'Egenföretagare restaurang' },
  { id: '320', label: 'Eldare' },
  { id: '321', label: 'Fastighetsskötare' },
  { id: '322', label: 'Florist' },
  { id: '323', label: 'Frukostvärdinna' },
  { id: '324', label: 'Grillkock' },
  { id: '325', label: 'Hotellchef' },
  { id: '326', label: 'Hotellreceptionist' },
  { id: '327', label: 'Hotellstädare' },
  { id: '328', label: 'Hovmästare' },
  { id: '329', label: 'Kallskänka' },
  { id: '330', label: 'Kock' },
  { id: '331', label: 'Köksansvarig' },
  { id: '332', label: 'Köksbiträde' },
  { id: '333', label: 'Köksmästare' },
  { id: '334', label: 'Mattläggare' },
  { id: '335', label: 'Nattportier' },
  { id: '336', label: 'Pizzabagare' },
  { id: '337', label: 'Restaurangbiträde' },
  { id: '338', label: 'Restaurangchef' },
  { id: '339', label: 'Restaurangföreståndare' },
  { id: '340', label: 'Room service' },
  { id: '341', label: 'Servitör' },
  { id: '342', label: 'Servitris' },
  { id: '343', label: 'Sommelier' },
  { id: '344', label: 'Souschef' },
  { id: '345', label: 'Städare' },
  { id: '346', label: 'Städledare' },
  { id: '347', label: 'Sushi-kock' },
  { id: '348', label: 'Trädgårdsanläggare' },
  { id: '349', label: 'Trädgårdsarbetare' },
  { id: '350', label: 'Trädgårdsmästare' },
  { id: '351', label: 'Vaktmästare' },
  { id: '352', label: 'Varuhusstädare' },

  // Städ & Service
  { id: '353', label: 'Flyttstädare' },
  { id: '354', label: 'Fönsterputsare' },
  { id: '355', label: 'Hemstädare' },
  { id: '356', label: 'Industristädare' },
  { id: '357', label: 'Kontorsstädare' },
  { id: '358', label: 'Lokalvårdare' },
  { id: '359', label: 'Skolstädare' },
  { id: '360', label: 'Städare' },
  { id: '361', label: 'Städledare' },
  { id: '362', label: 'Trappstädare' },
  { id: '363', label: 'Tvätteriarbetare' },

  // Media & Kommunikation
  { id: '364', label: 'Art director' },
  { id: '365', label: 'Content manager' },
  { id: '366', label: 'Content producer' },
  { id: '367', label: 'Copywriter' },
  { id: '368', label: 'Digital marketing specialist' },
  { id: '369', label: 'Fotograf' },
  { id: '370', label: 'Grafisk designer' },
  { id: '371', label: 'Illustratör' },
  { id: '372', label: 'Journalist' },
  { id: '373', label: 'Kommunikatör' },
  { id: '374', label: 'Kreativ chef' },
  { id: '375', label: 'Ljudtekniker' },
  { id: '376', label: 'Ljussättare' },
  { id: '377', label: 'Marknadsförare' },
  { id: '378', label: 'Media planner' },
  { id: '379', label: 'Medieproducent' },
  { id: '380', label: 'Medietekniker' },
  { id: '381', label: 'PR-assistent' },
  { id: '382', label: 'PR-chef' },
  { id: '383', label: 'PR-konsult' },
  { id: '384', label: 'Pressansvarig' },
  { id: '385', label: 'Pressfotograf' },
  { id: '386', label: 'Radiojournalist' },
  { id: '387', label: 'Radioproducent' },
  { id: '388', label: 'Redaktionschef' },
  { id: '389', label: 'Redaktionssekreterare' },
  { id: '390', label: 'Redaktör' },
  { id: '391', label: 'Reporter' },
  { id: '392', label: 'SEO-specialist' },
  { id: '393', label: 'Social media manager' },
  { id: '394', label: 'Streamingtekniker' },
  { id: '395', label: 'Technical writer' },
  { id: '396', label: 'Tekniker' },
  { id: '397', label: 'Textilarbetare' },
  { id: '398', label: 'TV-journalist' },
  { id: '399', label: 'TV-producent' },
  { id: '400', label: 'Videograf' },
  { id: '401', label: 'Videoredigerare' },
  { id: '402', label: 'Webbeditor' },
  { id: '403', label: 'Webbredaktör' },
  { id: '404', label: 'Översättare' },

  // Juridik & Säkerhet
  { id: '405', label: 'Advokat' },
  { id: '406', label: 'Advokatsekreterare' },
  { id: '407', label: 'Bevakningschef' },
  { id: '408', label: 'Bevakningspersonal' },
  { id: '409', label: 'Brandman' },
  { id: '410', label: 'Brandinspektör' },
  { id: '411', label: 'Brandingenjör' },
  { id: '412', label: 'Compliance officer' },
  { id: '413', label: 'Fältassistent' },
  { id: '414', label: 'Försäkringshandläggare' },
  { id: '415', label: 'Försäkringskonsulent' },
  { id: '416', label: 'Försäkringsrådgivare' },
  { id: '417', label: 'Handläggare' },
  { id: '418', label: 'Jurist' },
  { id: '419', label: 'Juristassistent' },
  { id: '420', label: 'Kriminalvårdare' },
  { id: '421', label: 'Myndighetsutövare' },
  { id: '422', label: 'Notarie' },
  { id: '423', label: 'Ordningsvakt' },
  { id: '424', label: 'Polis' },
  { id: '425', label: 'Rättssakkunnig' },
  { id: '426', label: 'Rättsläkare' },
  { id: '427', label: 'Säkerhetsansvarig' },
  { id: '428', label: 'Säkerhetschef' },
  { id: '429', label: 'Säkerhetskonsult' },
  { id: '430', label: 'Säkerhetskoordinator' },
  { id: '431', label: 'Väktare' },

  // Teknik & Ingenjör
  { id: '432', label: 'Applikationsingenjör' },
  { id: '433', label: 'Arkitekt' },
  { id: '434', label: 'Automationstekniker' },
  { id: '435', label: 'Beräkningsingenjör' },
  { id: '436', label: 'Civilingenjör' },
  { id: '437', label: 'Driftchef' },
  { id: '438', label: 'Driftsingenjör' },
  { id: '439', label: 'Elarbetare' },
  { id: '440', label: 'Elektroingenjör' },
  { id: '441', label: 'Elingenjör' },
  { id: '442', label: 'Fältsäljare' },
  { id: '443', label: 'Fälttekniker' },
  { id: '444', label: 'Högskoleingenjör' },
  { id: '445', label: 'Ingenjör' },
  { id: '446', label: 'Konstruktionsingenjör' },
  { id: '447', label: 'Konstruktör' },
  { id: '448', label: 'Kvalitetsingenjör' },
  { id: '449', label: 'Landskapsarkitekt' },
  { id: '450', label: 'Maskiningenjör' },
  { id: '451', label: 'Miljöingenjör' },
  { id: '452', label: 'Projekteringsingenjör' },
  { id: '453', label: 'Projektingenjör' },
  { id: '454', label: 'Projektör' },
  { id: '455', label: 'Provningsingenjör' },
  { id: '456', label: 'Rymdingenjör' },
  { id: '457', label: 'Serviceingenjör' },
  { id: '458', label: 'Sjöingenjör' },
  { id: '459', label: 'Systemingenjör' },
  { id: '460', label: 'Tekniker' },
  { id: '461', label: 'Teknisk chef' },
  { id: '462', label: 'Teknisk konsult' },
  { id: '463', label: 'Teknisk säljare' },
  { id: '464', label: 'Tekniskt ansvarig' },
  { id: '465', label: 'Tillverkningsingenjör' },

  // Ledning & Chefer
  { id: '466', label: 'Affärsområdeschef' },
  { id: '467', label: 'Avdelningschef' },
  { id: '468', label: 'Biträdande chef' },
  { id: '469', label: 'Bolagschef' },
  { id: '470', label: 'Business controller' },
  { id: '471', label: 'Business development manager' },
  { id: '472', label: 'Business manager' },
  { id: '473', label: 'Chef' },
  { id: '474', label: 'Chefsassistent' },
  { id: '475', label: 'Driftchef' },
  { id: '476', label: 'Enhetschef' },
  { id: '477', label: 'Finanschef' },
  { id: '478', label: 'Företagsledare' },
  { id: '479', label: 'Försäljningsdirektör' },
  { id: '480', label: 'General manager' },
  { id: '481', label: 'Gruppchef' },
  { id: '482', label: 'Koncernchef' },
  { id: '483', label: 'Kontorschef' },
  { id: '484', label: 'Ledningsassistent' },
  { id: '485', label: 'Managementkonsult' },
  { id: '486', label: 'Mellanchef' },
  { id: '487', label: 'Operativ chef' },
  { id: '488', label: 'Personalchef' },
  { id: '489', label: 'Produktionschef' },
  { id: '490', label: 'Projektchef' },
  { id: '491', label: 'Regionchef' },
  { id: '492', label: 'Servicechef' },
  { id: '493', label: 'Säljdirektör' },
  { id: '494', label: 'Team leader' },
  { id: '495', label: 'Teamledare' },
  { id: '496', label: 'Teknisk chef' },
  { id: '497', label: 'Verkställande direktör' },
  { id: '498', label: 'Vice VD' },
  { id: '499', label: 'VD' },
  { id: '500', label: 'VD-assistent' },
];
